### ISSUE TITLE
Is there a function for settings the max heap size and individual generation sizes?

### ISSUE THREAD

**Issue by FoxieFlakey** [GregorR/ggggc#2]

**Comment by FoxieFlakey** [comment]
and few statistics functions like getting heap usage, each generation usage and etc

**Comment by GregorR** [comment]
The sizes of the heap in general as well as each generation are adjusted based on use, so there is no function to manually set them. It wouldn't be too difficult to add one. There is not a function to get statistics, but there is a preprocessor directive, GGGGC_DEBUG_REPORT_COLLECTIONS, to make it _report_ statistics. That could easily be adapted.

**Comment by FoxieFlakey** [comment]
ok thanks i ask because i dont want waste time for something that might be
a thing
